using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KOAFiloServis.Web.Data.Migrations
{
    /// <inheritdoc />
    public partial class NihaiMimari_OrganizasyonSubeHolding : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ================================================================
            // Nihai Mimari (2026): Organizasyon, Sube, HoldingVeri, HoldingRapor
            // Idempotent SQL — her ortamda guvenle calisir.
            // ================================================================

            // 1. Organizasyonlar tablosu
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Organizasyonlar"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""Adi"" character varying(250) NOT NULL,
                    ""Kod"" character varying(20) NULL,
                    ""Aciklama"" character varying(500) NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL DEFAULT now(),
                    ""UpdatedAt"" timestamp without time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""DeletedAt"" timestamp without time zone NULL,
                    CONSTRAINT ""PK_Organizasyonlar"" PRIMARY KEY (""Id"")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Organizasyonlar_Kod""
                    ON ""Organizasyonlar"" (""Kod"") WHERE ""IsDeleted"" = false;
            ");

            // 2. Varsayilan Organizasyon kaydi (Ustun Holding)
            migrationBuilder.Sql(@"
                INSERT INTO ""Organizasyonlar"" (""Adi"", ""Kod"", ""IsDeleted"", ""CreatedAt"")
                SELECT 'Ustun Holding', 'USTUNHOLDING', false, now()
                WHERE NOT EXISTS (SELECT 1 FROM ""Organizasyonlar"" WHERE ""Kod"" = 'USTUNHOLDING');
            ");

            // 3. Subeler tablosu
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Subeler"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""FirmaId"" integer NOT NULL,
                    ""SubeAdi"" character varying(250) NOT NULL,
                    ""SubeKodu"" character varying(20) NULL,
                    ""Adres"" character varying(500) NULL,
                    ""Telefon"" character varying(20) NULL,
                    ""Aktif"" boolean NOT NULL DEFAULT true,
                    ""CreatedAt"" timestamp without time zone NOT NULL DEFAULT now(),
                    ""UpdatedAt"" timestamp without time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""DeletedAt"" timestamp without time zone NULL,
                    CONSTRAINT ""PK_Subeler"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Subeler_Firmalar_FirmaId""
                        FOREIGN KEY (""FirmaId"") REFERENCES ""Firmalar"" (""Id"") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Subeler_FirmaId_SubeKodu""
                    ON ""Subeler"" (""FirmaId"", ""SubeKodu"") WHERE ""IsDeleted"" = false;
            ");

            // 4. Firma.OrganizasyonId kolonu ve FK
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE ""Firmalar"" ADD COLUMN IF NOT EXISTS ""OrganizasyonId"" integer NOT NULL DEFAULT 1;
                EXCEPTION WHEN duplicate_column THEN END; $$;

                CREATE INDEX IF NOT EXISTS ""IX_Firmalar_OrganizasyonId""
                    ON ""Firmalar"" (""OrganizasyonId"");

                DO $$ BEGIN
                    ALTER TABLE ""Firmalar""
                    ADD CONSTRAINT ""FK_Firmalar_Organizasyonlar_OrganizasyonId""
                    FOREIGN KEY (""OrganizasyonId"") REFERENCES ""Organizasyonlar"" (""Id"") ON DELETE RESTRICT;
                EXCEPTION WHEN duplicate_table OR duplicate_object THEN END; $$;
            ");

            // 5. Mevcut firmalari Ustun Holding'e ata
            migrationBuilder.Sql(@"
                UPDATE ""Firmalar""
                SET ""OrganizasyonId"" = (SELECT ""Id"" FROM ""Organizasyonlar"" WHERE ""Kod"" = 'USTUNHOLDING' LIMIT 1)
                WHERE ""OrganizasyonId"" = 0 OR ""OrganizasyonId"" IS NULL
                   OR NOT EXISTS (SELECT 1 FROM ""Organizasyonlar"" o WHERE o.""Id"" = ""Firmalar"".""OrganizasyonId"");
            ");

            // 6. HoldingVeriler tablosu
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""HoldingVeriler"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""FirmaId"" integer NOT NULL,
                    ""FirmaKodu"" character varying(50) NOT NULL,
                    ""FirmaAdi"" character varying(250) NOT NULL,
                    ""Yil"" integer NOT NULL,
                    ""Ay"" integer NOT NULL,
                    ""Kategori"" character varying(50) NOT NULL,
                    ""ToplamGelir"" numeric NOT NULL DEFAULT 0,
                    ""ToplamGider"" numeric NOT NULL DEFAULT 0,
                    ""Kar"" numeric NOT NULL DEFAULT 0,
                    ""ButceHedef"" numeric NULL,
                    ""ButceGerceklesen"" numeric NULL,
                    ""AraclarMaliyet"" numeric NULL,
                    ""PersonelMaliyet"" numeric NULL,
                    ""HakedisToplam"" numeric NULL,
                    ""OdenmemisFaturaToplam"" numeric NULL,
                    ""AktifAracSayisi"" integer NULL,
                    ""PersonelSayisi"" integer NULL,
                    ""JsonDetay"" text NULL,
                    ""OlusturmaTarihi"" timestamp without time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_HoldingVeriler"" PRIMARY KEY (""Id"")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_HoldingVeriler_FirmaId_Yil_Ay_Kategori""
                    ON ""HoldingVeriler"" (""FirmaId"", ""Yil"", ""Ay"", ""Kategori"");
            ");

            // 7. HoldingRaporlar tablosu
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""HoldingRaporlar"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""Ad"" character varying(250) NOT NULL,
                    ""Tip"" character varying(50) NOT NULL,
                    ""Yil"" integer NOT NULL,
                    ""Ay"" integer NULL,
                    ""JsonFiltreler"" text NULL,
                    ""JsonSonuc"" text NULL,
                    ""OlusturmaTarihi"" timestamp without time zone NOT NULL DEFAULT now(),
                    ""OlusturanKullanici"" character varying(100) NULL,
                    CONSTRAINT ""PK_HoldingRaporlar"" PRIMARY KEY (""Id"")
                );
            ");

            // 8. DeletedAt kolonu (Kural 16) — tum BaseEntity tablolarina idempotent ekleme
            // Bu liste model snapshot'taki tum tablolari kapsar.
            var deletedAtTables = new[]
            {
                "AktiviteLoglar", "Araclar", "AracAlimSatimlar", "AracBakimUyarilari",
                "AracBolgeAtamalar", "AracBolgeler", "AracEvrakDosyaVersiyonlar",
                "AracEvrakDosyalari", "AracEvraklari", "AracIlanIcerikleri", "AracIlanYayinlar",
                "AracIlanlari", "AracIslemler", "AracKonumlar", "AracMaliyetSnapshotlari",
                "AracMarkaModeller", "AracMarkalari", "AracMasraflari", "AracModelleri",
                "AracOperasyonDurumlari", "AracPlakalar", "AracSatislari",
                "AracTakipAlarmlar", "AracTakipCihazlar", "AylikChecklistler",
                "AylikOdemeGerceklesenler", "AylikOdemePlanlari", "BakimPeriyotlar",
                "BankaHesaplari", "BankaKasaHareketleri", "BildirimAyarlari", "Bildirimler",
                "BordroAyarlar", "BordroDetaylar", "BordroOdemeler", "Bordrolar",
                "BudgetHedefler", "BudgetMasrafKalemleri", "BudgetOdemeler",
                "CariHatirlatmalar", "CariIletisimNotlar", "CariSeferUcretleri", "Cariler",
                "ChecklistKalemleri", "DashboardWidgetlar", "DestekAyarlari",
                "DestekBilgiBankasiMakaleleri", "DestekDepartmanUyeleri",
                "DestekDepartmanlari", "DestekHazirYanitlari", "DestekKategorileri",
                "DestekSlaListesi", "DestekTalebiAktiviteleri", "DestekTalebiEkleri",
                "DestekTalebiIliskileri", "DestekTalebiYanitlari", "DestekTalepleri",
                "EbysAramaGecmisleri", "EbysBelgeEmbeddingler", "EbysEvrakAtamalar",
                "EbysEvrakDosyaVersiyonlar", "EbysEvrakDosyalar", "EbysEvrakHareketler",
                "EbysEvrakKategoriler", "EbysEvraklar", "EbysKayitliAramalar",
                "EmailAyarlari", "EpostaBildirimLoglari", "FaturaKalemleri", "FaturaSablonlari",
                "Faturalar", "FiloGunlukPuantajlar", "FiloGuzergahEslestirmeleri",
                "FirmaAracSoforEslestirmeleri", "FirmaGuzergahEslestirmeleri",
                "Firmalar", "FirmalarArasiTransferler", "GunlukPuantajlar", "GuzergahSeferleri",
                "Guzergahlar", "HakedisDetaylari", "Hakedisler", "Hatirlaticilar",
                "IhaleGuzergahKalemleri", "IhaleProjeleri", "IhaleRakipBenchmarklar",
                "IhaleSozlesmeRevizyonlari", "IhaleTeklifKararLoglari",
                "IhaleTeklifVersiyonlari", "IlanPlatformlari", "Kapasiteler",
                "KdvHesapEslestirmeleri", "KiralamaAraclar", "KiralikCPlakaTakipler",
                "KiralikPlakaTakipler", "KostMerkezleri", "KullaniciCariler",
                "KullaniciSonIslemler", "KullaniciTercihleri", "Kullanicilar", "Kurumlar",
                "LastikDegisimler", "LastikDepolar", "LastikSezonAyarlari", "LastikStoklar",
                "Lisanslar", "MasrafKalemleri", "Mesajlar", "MuhasebeAyarlari",
                "MuhasebeDonemleri", "MuhasebeFisKalemleri", "MuhasebeFisleri",
                "MuhasebeHesaplari", "MuhasebeProjeler", "MusteriKiralamalar",
                "OdemeEslestirmeleri", "OperasyonKayitlari", "OzlukEvrakTanimlari",
                "PersonelAracAtamalari", "PersonelAvansMahsuplar", "PersonelAvanslar",
                "PersonelBorcOdemeler", "PersonelBorclar", "PersonelFinansAyarlar",
                "PersonelIzinHaklari", "PersonelIzinleri", "PersonelMaaslari",
                "PersonelOzlukEvrakVersiyonlar", "PersonelOzlukEvraklar",
                "PersonelPuantajlar", "Personeller", "PiyasaArastirmaIlanlar",
                "PiyasaArastirmalar", "PiyasaIlanlari", "PlakaDonusumler",
                "ProformaFaturaKalemler", "ProformaFaturalar", "PuantajAuditLogs",
                "PuantajDetaylari", "PuantajEslestirmeOnerileri", "PuantajExcelImportlar",
                "PuantajFinansalKayitlar", "PuantajHesapDonemleri", "PuantajJobExecutions",
                "PuantajKayitlar", "RolYetkileri", "Roller", "SatisPersonelleri",
                "ServisCalismaKiralamalar", "ServisCalismalari", "ServisKayitlari",
                "ServisKontratlar", "ServisOdemeler", "ServisParcalar", "ServisPuantajlar",
                "ServisTahsilatlar", "SmsAyarlari", "SmsLoglari", "SmsSablonlari",
                "StokHareketler", "StokKartlari", "StokKategoriler",
                "TasimaTedarikciIsler", "TasimaTedarikciler", "TedarikciEvrakDosyalari",
                "TedarikciEvraklari", "TekrarlayanOdemeler", "WebhookEndpointler",
                "WebhookLoglar", "WhatsAppAyarlari", "WhatsAppGrupUyeler",
                "WhatsAppGruplar", "WhatsAppKisiler", "WhatsAppMesajlar", "WhatsAppSablonlar"
            };

            foreach (var table in deletedAtTables)
            {
                migrationBuilder.Sql($@"
                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '{table}') THEN
                            EXECUTE 'ALTER TABLE ""{table}"" ADD COLUMN IF NOT EXISTS ""DeletedAt"" timestamp without time zone NULL';
                        END IF;
                    END; $$;
                ");
            }

            // 9. FirmaId NOT NULL + FK: Kategori B entity'leri (yeni IFirmaTenant)
            var notNullFirmaIdTables = new[]
            {
                "BordroAyarlar", "BordroDetaylar", "Bordrolar",
                "CariHatirlatmalar", "IhaleProjeleri", "PersonelAvanslar",
                "PersonelBorclar", "PersonelFinansAyarlar", "ProformaFaturalar",
                "PuantajAuditLogs", "TekrarlayanOdemeler"
            };

            foreach (var table in notNullFirmaIdTables)
            {
                // NULL FirmaId'leri ilk gecerli FirmaId ile doldur, sonra NOT NULL yap.
                migrationBuilder.Sql($@"
                    DO $$ DECLARE first_firma_id integer;
                    BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '{table}') THEN
                            SELECT ""Id"" INTO first_firma_id FROM ""Firmalar"" WHERE NOT ""IsDeleted"" ORDER BY ""Id"" LIMIT 1;
                            IF first_firma_id IS NOT NULL THEN
                                EXECUTE 'UPDATE ""{table}"" SET ""FirmaId"" = ' || first_firma_id || ' WHERE ""FirmaId"" IS NULL OR ""FirmaId"" = 0';
                                EXECUTE 'ALTER TABLE ""{table}"" ALTER COLUMN ""FirmaId"" SET NOT NULL';
                            END IF;
                        END IF;
                    END; $$;
                ");
            }

            // 10. FirmaId FK ekle: daha once FK'si olmayan tablolara

            // 10. FirmaId FK ekle: daha once FK'si olmayan tablolara
            var fkMappings = new (string table, string fkName, string onDelete)[]
            {
                ("BordroAyarlar", "FK_BordroAyarlar_Firmalar_FirmaId", "CASCADE"),
                ("BordroDetaylar", "FK_BordroDetaylar_Firmalar_FirmaId", "CASCADE"),
                ("Bordrolar", "FK_Bordrolar_Firmalar_FirmaId", "CASCADE"),
                ("CariHatirlatmalar", "FK_CariHatirlatmalar_Firmalar_FirmaId", "CASCADE"),
                ("FiloGunlukPuantajlar", "FK_FiloGunlukPuantajlar_Firmalar_FirmaId", "RESTRICT"),
                ("FiloGuzergahEslestirmeleri", "FK_FiloGuzergahEslestirmeleri_Firmalar_FirmaId", "RESTRICT"),
                ("FirmaAracSoforEslestirmeleri", "FK_FirmaAracSoforEslestirmeleri_Firmalar_FirmaId", "CASCADE"),
                ("FirmaGuzergahEslestirmeleri", "FK_FirmaGuzergahEslestirmeleri_Firmalar_FirmaId", "CASCADE"),
                ("IhaleProjeleri", "FK_IhaleProjeleri_Firmalar_FirmaId", "CASCADE"),
                ("MusteriKiralamalar", "FK_MusteriKiralamalar_Firmalar_FirmaId", "CASCADE"),
                ("OperasyonKayitlari", "FK_OperasyonKayitlari_Firmalar_FirmaId", "CASCADE"),
                ("PersonelAvanslar", "FK_PersonelAvanslar_Firmalar_FirmaId", "CASCADE"),
                ("PersonelBorclar", "FK_PersonelBorclar_Firmalar_FirmaId", "CASCADE"),
                ("PersonelFinansAyarlar", "FK_PersonelFinansAyarlar_Firmalar_FirmaId", "CASCADE"),
                ("PuantajAuditLogs", "FK_PuantajAuditLogs_Firmalar_FirmaId", "CASCADE"),
                ("PuantajDetaylari", "FK_PuantajDetaylari_Firmalar_FirmaId", "CASCADE"),
                ("PuantajFinansalKayitlar", "FK_PuantajFinansalKayitlar_Firmalar_FirmaId", "CASCADE"),
                ("PuantajHesapDonemleri", "FK_PuantajHesapDonemleri_Firmalar_FirmaId", "CASCADE"),
                ("PuantajJobExecutions", "FK_PuantajJobExecutions_Firmalar_FirmaId", "CASCADE"),
            };

            foreach (var (table, fkName, onDelete) in fkMappings)
            {
                // FK zaten varsa ekleme (information_schema'dan kontrol)
                migrationBuilder.Sql($@"
                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '{table}')
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                               WHERE constraint_name = '{fkName}' AND table_name = '{table}') THEN
                            EXECUTE 'ALTER TABLE ""{table}"" ADD CONSTRAINT ""{fkName}"" FOREIGN KEY (""FirmaId"") REFERENCES ""Firmalar"" (""Id"") ON DELETE {onDelete}';
                        END IF;
                    EXCEPTION WHEN duplicate_table OR duplicate_object THEN END; $$;
                ");
            }

            // 11. FirmaId indeksleri — yeni IFirmaTenant entity'leri icin
            var indexTables = new[]
            {
                "PuantajFinansalKayitlar", "PuantajDetaylari", "MusteriKiralamalar",
                "FiloGuzergahEslestirmeleri", "FiloGunlukPuantajlar"
            };

            foreach (var table in indexTables)
            {
                migrationBuilder.Sql($@"
                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '{table}') THEN
                            EXECUTE 'CREATE INDEX IF NOT EXISTS ""IX_{table}_FirmaId"" ON ""{table}"" (""FirmaId"")';
                        END IF;
                    END; $$;
                ");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Down migrasyonu: idempotent degil — geri alma istege bagli.
            // Tablolari sil, kolonlari kaldir.
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""HoldingRaporlar"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""HoldingVeriler"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Subeler"" CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""Firmalar"" DROP COLUMN IF EXISTS ""OrganizasyonId"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Organizasyonlar"" CASCADE;");
        }
    }
}
