using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KOAFiloServis.Web.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddSnapshotHakedisFieldsV2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tablo henüz oluşmamış olabilir (önceki migration applied ama DB yok)
            // Idempotent: önce tabloyu oluştur, sonra kolon ekle
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""MaasOdemeSnapshotlar"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""FirmaId"" integer NOT NULL DEFAULT 0,
                    ""Yil"" integer NOT NULL,
                    ""Ay"" integer NOT NULL,
                    ""PersonelId"" integer NOT NULL,
                    ""PersonelAdSoyad"" text NOT NULL DEFAULT '',
                    ""PersonelKodu"" text NULL,
                    ""GorevAdi"" text NULL,
                    ""AracPlakasi"" text NULL,
                    ""GercekMaas"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""BankayaYatan"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""Avans"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""Kesinti"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""Harcama"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""Odenecek"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""MuhasebeFisId"" integer NULL,
                    ""IptalFisId"" integer NULL,
                    ""HesaplamaTarihi"" timestamp without time zone NOT NULL DEFAULT NOW(),
                    ""Kilitli"" boolean NOT NULL DEFAULT true,
                    ""CreatedAt"" timestamp without time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp without time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""DeletedAt"" timestamp without time zone NULL,
                    ""DeletedBy"" integer NULL,
                    CONSTRAINT ""PK_MaasOdemeSnapshotlar"" PRIMARY KEY (""Id"")
                );
            ");

            // İndex (varsa hata vermez)
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_MaasOdemeSnapshotlar_FirmaId_Yil_Ay""
                ON ""MaasOdemeSnapshotlar"" (""FirmaId"", ""Yil"", ""Ay"");
            ");

            // Yeni Hakedis kolonları (idempotent)
            migrationBuilder.Sql(@"
                ALTER TABLE ""MaasOdemeSnapshotlar""
                ADD COLUMN IF NOT EXISTS ""HakedisGelir"" numeric(18,2) NOT NULL DEFAULT 0;
            ");
            migrationBuilder.Sql(@"
                ALTER TABLE ""MaasOdemeSnapshotlar""
                ADD COLUMN IF NOT EXISTS ""HakedisGider"" numeric(18,2) NOT NULL DEFAULT 0;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""MaasOdemeSnapshotlar"" DROP COLUMN IF EXISTS ""HakedisGelir"";
            ");
            migrationBuilder.Sql(@"
                ALTER TABLE ""MaasOdemeSnapshotlar"" DROP COLUMN IF EXISTS ""HakedisGider"";
            ");
        }
    }
}
