using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace KOAFiloServis.Web.Data.Migrations;

/// <summary>
/// Idempotent migration helper: creates tables and columns introduced by
/// SyncPuantajSchema migration on tenant databases that were created before
/// the migration existed. Uses CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.
/// Safe to run on both new and old tenant DBs — no-op if already applied.
/// </summary>
public static class SyncPuantajSchemaMigrationHelper
{
    public static async Task ApplyAsync(ApplicationDbContext ctx, ILogger? logger = null)
    {
        logger?.LogInformation("SyncPuantajSchemaMigrationHelper: checking tenant DB schema...");

        // ── New tables (CREATE IF NOT EXISTS) ──────────────────────────

        await ctx.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""OperasyonKayitlari"" (
                ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                ""FirmaId"" integer NOT NULL,
                ""Tarih"" timestamp without time zone NOT NULL,
                ""GuzergahId"" integer NOT NULL,
                ""AracId"" integer NOT NULL,
                ""SoforId"" integer NULL,
                ""Slot"" integer NOT NULL,
                ""SlotAdi"" character varying(50) NULL,
                ""Yon"" integer NOT NULL,
                ""KurumId"" integer NULL,
                ""IsverenFirmaId"" integer NULL,
                ""SeferSayisi"" integer NOT NULL,
                ""PuantajCarpani"" numeric(10,2) NOT NULL,
                ""OperasyonDurumu"" integer NOT NULL,
                ""KaynakTipi"" integer NOT NULL,
                ""FinansYonu"" integer NOT NULL,
                ""SoforOdemeTipi"" integer NOT NULL,
                ""OdemeYapilacakCariId"" integer NULL,
                ""FaturaKesiciCariId"" integer NULL,
                ""BelgeNo"" character varying(50) NULL,
                ""TransferDurum"" character varying(50) NULL,
                ""Kaynak"" integer NOT NULL,
                ""ExcelImportId"" integer NULL,
                ""ExcelSatirNo"" integer NULL,
                ""CreatedBy"" character varying(100) NULL,
                ""UpdatedBy"" character varying(100) NULL,
                ""DeletedAt"" timestamp without time zone NULL,
                ""DeletedBy"" character varying(100) NULL,
                ""Notlar"" character varying(1000) NULL,
                ""CreatedAt"" timestamp without time zone NOT NULL,
                ""UpdatedAt"" timestamp without time zone NULL,
                ""IsDeleted"" boolean NOT NULL,
                CONSTRAINT ""PK_OperasyonKayitlari"" PRIMARY KEY (""Id"")
            );
        ");

        await ctx.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""PuantajJobExecutions"" (
                ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                ""FirmaId"" integer NULL,
                ""Yil"" integer NOT NULL,
                ""Ay"" integer NOT NULL,
                ""KurumId"" integer NULL,
                ""Tetikleyen"" character varying(50) NOT NULL,
                ""Durum"" integer NOT NULL,
                ""Baslangic"" timestamp without time zone NULL,
                ""Bitis"" timestamp without time zone NULL,
                ""Versiyon"" integer NOT NULL,
                ""HesapDonemiId"" integer NULL,
                ""IslenenOperasyon"" integer NOT NULL,
                ""UretilenPuantaj"" integer NOT NULL,
                ""HataMesaji"" text NULL,
                ""Hesaplayan"" character varying(100) NULL,
                ""CreatedAt"" timestamp without time zone NOT NULL,
                ""UpdatedAt"" timestamp without time zone NULL,
                ""IsDeleted"" boolean NOT NULL,
                CONSTRAINT ""PK_PuantajJobExecutions"" PRIMARY KEY (""Id"")
            );
        ");

        await ctx.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""PuantajHesapDonemleri"" (
                ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                ""FirmaId"" integer NULL,
                ""Yil"" integer NOT NULL,
                ""Ay"" integer NOT NULL,
                ""KurumId"" integer NULL,
                ""Versiyon"" integer NOT NULL,
                ""Durum"" integer NOT NULL,
                ""OncekiDonemId"" integer NULL,
                ""IslenenOperasyonSayisi"" integer NOT NULL,
                ""UretilenPuantajSayisi"" integer NOT NULL,
                ""CreatedAt"" timestamp without time zone NOT NULL,
                ""UpdatedAt"" timestamp without time zone NULL,
                ""IsDeleted"" boolean NOT NULL,
                CONSTRAINT ""PK_PuantajHesapDonemleri"" PRIMARY KEY (""Id"")
            );
        ");

        await ctx.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""PuantajDetaylari"" (
                ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                ""FirmaId"" integer NULL,
                ""OperasyonKaydiId"" integer NOT NULL,
                ""PuantajKayitId"" integer NOT NULL,
                ""HesapDonemiId"" integer NOT NULL,
                ""BirimGelir"" numeric NOT NULL,
                ""BirimGider"" numeric NOT NULL,
                ""SeferSayisi"" integer NOT NULL,
                ""HesaplananTutar"" numeric NOT NULL,
                ""CreatedAt"" timestamp without time zone NOT NULL,
                ""UpdatedAt"" timestamp without time zone NULL,
                ""IsDeleted"" boolean NOT NULL,
                CONSTRAINT ""PK_PuantajDetaylari"" PRIMARY KEY (""Id"")
            );
        ");

        await ctx.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""PuantajFinansalKayitlar"" (
                ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                ""FirmaId"" integer NULL,
                ""PuantajKayitId"" integer NOT NULL,
                ""HesapDonemiId"" integer NOT NULL,
                ""CariId"" integer NULL,
                ""Tutar"" numeric NOT NULL,
                ""Yon"" integer NOT NULL,
                ""Aciklama"" character varying(500) NULL,
                ""CreatedAt"" timestamp without time zone NOT NULL,
                ""UpdatedAt"" timestamp without time zone NULL,
                ""IsDeleted"" boolean NOT NULL,
                CONSTRAINT ""PK_PuantajFinansalKayitlar"" PRIMARY KEY (""Id"")
            );
        ");

        await ctx.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""PuantajAuditLogs"" (
                ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                ""FirmaId"" integer NULL,
                ""PuantajKayitId"" integer NOT NULL,
                ""HesapDonemiId"" integer NOT NULL,
                ""Islem"" integer NOT NULL,
                ""EskiDeger"" text NULL,
                ""YeniDeger"" text NULL,
                ""YapanKullanici"" character varying(100) NULL,
                ""CreatedAt"" timestamp without time zone NOT NULL,
                ""IsDeleted"" boolean NOT NULL,
                CONSTRAINT ""PK_PuantajAuditLogs"" PRIMARY KEY (""Id"")
            );
        ");

        // ── Indexes ─────────────────────────────────────────────────────

        // PuantajKayitlar: partial UNIQUE index (soft-delete safe).
        // Only constrains rows WHERE "IsDeleted" = false.
        // Soft-deleted rows are excluded — engine re-runs create new versions
        // without old soft-deleted rows blocking the unique key space.
        // This is the canonical PostgreSQL soft-delete uniqueness pattern.
        await ctx.Database.ExecuteSqlRawAsync(@"
            DROP INDEX IF EXISTS ""IX_PuantajKayitlar_Yil_Ay_GuzergahId_AracId_Slot"";
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PuantajKayitlar_Yil_Ay_GuzergahId_AracId_Slot""
                ON ""PuantajKayitlar"" (""Yil"", ""Ay"", ""GuzergahId"", ""AracId"", ""Slot"")
                WHERE ""IsDeleted"" = false;
        ");

        await ctx.Database.ExecuteSqlRawAsync(@"
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_OperasyonKayitlari_Tarih_GuzergahId_AracId_Slot""
                ON ""OperasyonKayitlari"" (""Tarih"", ""GuzergahId"", ""AracId"", ""Slot"");
            CREATE INDEX IF NOT EXISTS ""IX_OperasyonKayitlari_Tarih"" ON ""OperasyonKayitlari"" (""Tarih"");
            CREATE INDEX IF NOT EXISTS ""IX_OperasyonKayitlari_OperasyonDurumu"" ON ""OperasyonKayitlari"" (""OperasyonDurumu"");
            CREATE INDEX IF NOT EXISTS ""IX_OperasyonKayitlari_Slot"" ON ""OperasyonKayitlari"" (""Slot"");
            CREATE INDEX IF NOT EXISTS ""IX_OperasyonKayitlari_FirmaId_Tarih"" ON ""OperasyonKayitlari"" (""FirmaId"", ""Tarih"");
            CREATE INDEX IF NOT EXISTS ""IX_OperasyonKayitlari_Tarih_KurumId"" ON ""OperasyonKayitlari"" (""Tarih"", ""KurumId"");
            CREATE INDEX IF NOT EXISTS ""IX_OperasyonKayitlari_Tarih_AracId"" ON ""OperasyonKayitlari"" (""Tarih"", ""AracId"");
            CREATE INDEX IF NOT EXISTS ""IX_PuantajDetaylari_OperasyonKaydiId_HesapDonemiId""
                ON ""PuantajDetaylari"" (""OperasyonKaydiId"", ""HesapDonemiId"");
        ");

        // PuantajJobExecutions: unique filtered index for mutex.
        // Only one Running entry allowed per (FirmaId, Yil, Ay).
        // EF model: .HasIndex(...).IsUnique().HasFilter("\"Durum\" = 0")
        await ctx.Database.ExecuteSqlRawAsync(@"
            DROP INDEX IF EXISTS ""IX_PuantajJobExecutions_FirmaId_Yil_Ay"";
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PuantajJobExecutions_FirmaId_Yil_Ay""
                ON ""PuantajJobExecutions"" (""FirmaId"", ""Yil"", ""Ay"")
                WHERE ""Durum"" = 0;
        ");

        // ── PuantajKayitlar: idempotent column adds ────────────────────

        var puantajColumns = new[]
        {
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"BelgeNo\" character varying(50) NULL",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"FinansYonu\" integer NOT NULL DEFAULT 0",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"HesapDonemiId\" integer NULL",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"IsverenFirmaId\" integer NULL",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"KaynakTipi\" integer NOT NULL DEFAULT 0",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"KurumId\" integer NULL",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"OncekiVersiyonId\" integer NULL",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"Slot\" integer NOT NULL DEFAULT 0",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"SlotAdi\" character varying(50) NULL",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"TransferDurum\" character varying(50) NULL",
            "ALTER TABLE \"PuantajKayitlar\" ADD COLUMN IF NOT EXISTS \"Versiyon\" integer NOT NULL DEFAULT 1",
        };

        foreach (var col in puantajColumns)
        {
            try { await ctx.Database.ExecuteSqlRawAsync(col); }
            catch { /* column may already exist with different default; ignore */ }
        }

        // ── PuantajHesapDonemleri: idempotent column adds ───────────────

        var hesapDonemColumns = new[]
        {
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"HesaplayanKullanici\" character varying(100) NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"HesaplamaTarihi\" timestamp without time zone NOT NULL DEFAULT now()",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"Notlar\" character varying(500) NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"OnayDurum\" integer NOT NULL DEFAULT 0",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"FinansOnaylayan\" character varying(100) NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"FinansOnayTarihi\" timestamp without time zone NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"MuhasebeOnaylayan\" character varying(100) NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"MuhasebeOnayTarihi\" timestamp without time zone NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"KilitTarihi\" timestamp without time zone NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"KilitAciklama\" character varying(100) NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"CreatedBy\" character varying(100) NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"UpdatedBy\" character varying(100) NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"DeletedAt\" timestamp without time zone NULL",
            "ALTER TABLE \"PuantajHesapDonemleri\" ADD COLUMN IF NOT EXISTS \"DeletedBy\" character varying(100) NULL",
        };

        foreach (var col in hesapDonemColumns)
        {
            try { await ctx.Database.ExecuteSqlRawAsync(col); }
            catch { /* column may already exist; ignore */ }
        }

        // ── Sequence reset for new tables ──────────────────────────────

        var newTables = new[] { "OperasyonKayitlari", "PuantajJobExecutions", "PuantajHesapDonemleri",
                                "PuantajDetaylari", "PuantajFinansalKayitlar", "PuantajAuditLogs" };
        foreach (var tbl in newTables)
        {
            try
            {
                // EF1002: DDL ile sistem tarafindan uretilen tablo adi kullaniliyor, kullanici girdisi yok
#pragma warning disable EF1002
                await ctx.Database.ExecuteSqlRawAsync($"""
                    SELECT setval(pg_get_serial_sequence('"{tbl}"', 'Id'),
                        COALESCE((SELECT MAX("Id") FROM "{tbl}"), 0) + 1, false);
                    """);
#pragma warning restore EF1002
            }
            catch { }
        }

        logger?.LogInformation("SyncPuantajSchemaMigrationHelper: completed.");
    }
}
