using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MKFiloServis.Web.Data.Migrations
{
    /// <inheritdoc />
    public partial class CRMModulu : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: kolon zaten varsa hata vermez
                migrationBuilder.Sql(
                    """
                    DO $$ BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'Roller' AND column_name = 'Renk'
                        ) THEN
                            ALTER TABLE "Roller" ADD "Renk" text;
                        END IF;
                    END $$;
                    """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Bildirimler" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KullaniciId" integer NOT NULL,
                    "Baslik" character varying(200) NOT NULL,
                    "Icerik" character varying(1000),
                    "Tip" integer NOT NULL,
                    "Oncelik" integer NOT NULL,
                    "Okundu" boolean NOT NULL,
                    "OkunmaTarihi" timestamp without time zone,
                    "IliskiliTablo" character varying(50),
                    "IliskiliKayitId" integer,
                    "Link" character varying(200),
                    "SonGosterimTarihi" timestamp without time zone,
                    "Tekrarli" boolean NOT NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone,
                    "IsDeleted" boolean NOT NULL,
                    CONSTRAINT "PK_Bildirimler" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Bildirimler_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "DashboardWidgetlar" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KullaniciId" integer NOT NULL,
                    "WidgetKodu" character varying(50) NOT NULL,
                    "Sira" integer NOT NULL,
                    "Kolon" integer NOT NULL,
                    "Genislik" integer NOT NULL,
                    "Gorunur" boolean NOT NULL,
                    "Kucultulmus" boolean NOT NULL,
                    "Ayarlar" character varying(2000),
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone,
                    "IsDeleted" boolean NOT NULL,
                    CONSTRAINT "PK_DashboardWidgetlar" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DashboardWidgetlar_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "EmailAyarlari" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KullaniciId" integer,
                    "SmtpSunucu" character varying(100) NOT NULL,
                    "SmtpPort" integer NOT NULL,
                    "SslKullan" boolean NOT NULL,
                    "Email" character varying(100) NOT NULL,
                    "Sifre" character varying(100),
                    "GonderenAdi" character varying(100),
                    "Aktif" boolean NOT NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone,
                    "IsDeleted" boolean NOT NULL,
                    CONSTRAINT "PK_EmailAyarlari" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_EmailAyarlari_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Hatirlaticilar" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KullaniciId" integer NOT NULL,
                    "Baslik" character varying(200) NOT NULL,
                    "Aciklama" character varying(1000),
                    "Tip" integer NOT NULL,
                    "BaslangicTarihi" timestamp without time zone NOT NULL,
                    "BitisTarihi" timestamp without time zone,
                    "TumGun" boolean NOT NULL,
                    "TekrarTipi" integer NOT NULL,
                    "TekrarAraligi" integer NOT NULL,
                    "TekrarBitisTarihi" timestamp without time zone,
                    "BildirimDakikaOnce" integer NOT NULL,
                    "EmailBildirim" boolean NOT NULL,
                    "PushBildirim" boolean NOT NULL,
                    "IliskiliTablo" character varying(50),
                    "IliskiliKayitId" integer,
                    "Durum" integer NOT NULL,
                    "Renk" character varying(20),
                    "CariId" integer,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone,
                    "IsDeleted" boolean NOT NULL,
                    CONSTRAINT "PK_Hatirlaticilar" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Hatirlaticilar_Cariler_CariId" FOREIGN KEY ("CariId")
                        REFERENCES "Cariler" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_Hatirlaticilar_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "KullaniciCariler" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KullaniciId" integer NOT NULL,
                    "CariId" integer NOT NULL,
                    "EkstreGorebilir" boolean NOT NULL,
                    "FaturaGorebilir" boolean NOT NULL,
                    "OdemeYapabilir" boolean NOT NULL,
                    "DuzenlemeYapabilir" boolean NOT NULL,
                    "Tip" integer NOT NULL,
                    "Not" character varying(500),
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone,
                    "IsDeleted" boolean NOT NULL,
                    CONSTRAINT "PK_KullaniciCariler" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_KullaniciCariler_Cariler_CariId" FOREIGN KEY ("CariId")
                        REFERENCES "Cariler" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_KullaniciCariler_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Mesajlar" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "GonderenId" integer NOT NULL,
                    "AliciId" integer,
                    "Konu" character varying(200) NOT NULL,
                    "Icerik" text NOT NULL,
                    "Tip" integer NOT NULL,
                    "Durum" integer NOT NULL,
                    "Okundu" boolean NOT NULL,
                    "OkunmaTarihi" timestamp without time zone,
                    "DisAlici" character varying(100),
                    "DisGonderimId" character varying(100),
                    "UstMesajId" integer,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone,
                    "IsDeleted" boolean NOT NULL,
                    CONSTRAINT "PK_Mesajlar" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Mesajlar_Kullanicilar_AliciId" FOREIGN KEY ("AliciId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_Mesajlar_Kullanicilar_GonderenId" FOREIGN KEY ("GonderenId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_Mesajlar_Mesajlar_UstMesajId" FOREIGN KEY ("UstMesajId")
                        REFERENCES "Mesajlar" ("Id") ON DELETE SET NULL
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "WhatsAppAyarlari" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KullaniciId" integer,
                    "Telefon" character varying(20),
                    "ApiKey" character varying(500),
                    "WebhookUrl" character varying(200),
                    "Aktif" boolean NOT NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone,
                    "IsDeleted" boolean NOT NULL,
                    CONSTRAINT "PK_WhatsAppAyarlari" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_WhatsAppAyarlari_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId")
                        REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_Bildirimler_KullaniciId_Okundu\" ON \"Bildirimler\" (\"KullaniciId\", \"Okundu\");");

            migrationBuilder.Sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_DashboardWidgetlar_KullaniciId_WidgetKodu\" ON \"DashboardWidgetlar\" (\"KullaniciId\", \"WidgetKodu\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_EmailAyarlari_KullaniciId\" ON \"EmailAyarlari\" (\"KullaniciId\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_Hatirlaticilar_CariId\" ON \"Hatirlaticilar\" (\"CariId\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_Hatirlaticilar_KullaniciId_BaslangicTarihi\" ON \"Hatirlaticilar\" (\"KullaniciId\", \"BaslangicTarihi\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_KullaniciCariler_CariId\" ON \"KullaniciCariler\" (\"CariId\");");

            migrationBuilder.Sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_KullaniciCariler_KullaniciId_CariId\" ON \"KullaniciCariler\" (\"KullaniciId\", \"CariId\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_Mesajlar_AliciId_Okundu\" ON \"Mesajlar\" (\"AliciId\", \"Okundu\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_Mesajlar_GonderenId\" ON \"Mesajlar\" (\"GonderenId\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_Mesajlar_UstMesajId\" ON \"Mesajlar\" (\"UstMesajId\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_WhatsAppAyarlari_KullaniciId\" ON \"WhatsAppAyarlari\" (\"KullaniciId\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_WhatsAppAyarlari_KullaniciId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Mesajlar_UstMesajId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Mesajlar_GonderenId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Mesajlar_AliciId_Okundu\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_KullaniciCariler_KullaniciId_CariId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_KullaniciCariler_CariId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Hatirlaticilar_KullaniciId_BaslangicTarihi\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Hatirlaticilar_CariId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_EmailAyarlari_KullaniciId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_DashboardWidgetlar_KullaniciId_WidgetKodu\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Bildirimler_KullaniciId_Okundu\";");

            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Bildirimler\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"DashboardWidgetlar\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"EmailAyarlari\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Hatirlaticilar\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"KullaniciCariler\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Mesajlar\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"WhatsAppAyarlari\";");

            migrationBuilder.Sql(
                """
                DO $$ BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Roller' AND column_name = 'Renk'
                    ) THEN
                        ALTER TABLE "Roller" DROP COLUMN "Renk";
                    END IF;
                END $$;
                """);
        }
    }
}


