using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MKFiloServis.Web.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260924233000_RentACarKaraListe")]
public sealed class RentACarKaraListe : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "RentACarKaraListeKayitlari" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FirmaId" integer NOT NULL,
                    "MusteriId" integer NOT NULL,
                    "Neden" character varying(500) NOT NULL,
                    "EkleyenKullaniciId" integer NOT NULL,
                    "KaldirmaTarihi" timestamp without time zone NULL,
                    "KaldiranKullaniciId" integer NULL,
                    "KaldirmaNedeni" character varying(500) NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NULL,
                    "IsDeleted" boolean NOT NULL,
                    "DeletedAt" timestamp without time zone NULL,
                    "DeletedBy" integer NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_RentACarKaraListeKayitlari_FirmaId_MusteriId"
                    ON "RentACarKaraListeKayitlari" ("FirmaId", "MusteriId");
                CREATE INDEX IF NOT EXISTS "IX_RentACarKaraListeKayitlari_MusteriId"
                    ON "RentACarKaraListeKayitlari" ("MusteriId");
                """);
            return;
        }

        migrationBuilder.CreateTable(
            name: "RentACarKaraListeKayitlari",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true),
                FirmaId = table.Column<int>(nullable: false),
                MusteriId = table.Column<int>(nullable: false),
                Neden = table.Column<string>(maxLength: 500, nullable: false),
                EkleyenKullaniciId = table.Column<int>(nullable: false),
                KaldirmaTarihi = table.Column<DateTime>(nullable: true),
                KaldiranKullaniciId = table.Column<int>(nullable: true),
                KaldirmaNedeni = table.Column<string>(maxLength: 500, nullable: true),
                CreatedAt = table.Column<DateTime>(nullable: false),
                UpdatedAt = table.Column<DateTime>(nullable: true),
                IsDeleted = table.Column<bool>(nullable: false),
                DeletedAt = table.Column<DateTime>(nullable: true),
                DeletedBy = table.Column<int>(nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_RentACarKaraListeKayitlari", x => x.Id);
                table.ForeignKey("FK_RentACarKaraListeKayitlari_Firmalar_FirmaId", x => x.FirmaId, "Firmalar", "Id", onDelete: ReferentialAction.Restrict);
                table.ForeignKey("FK_RentACarKaraListeKayitlari_Cariler_MusteriId", x => x.MusteriId, "Cariler", "Id", onDelete: ReferentialAction.Restrict);
            });
        migrationBuilder.CreateIndex("IX_RentACarKaraListeKayitlari_FirmaId_MusteriId", "RentACarKaraListeKayitlari", new[] { "FirmaId", "MusteriId" });
        migrationBuilder.CreateIndex("IX_RentACarKaraListeKayitlari_MusteriId", "RentACarKaraListeKayitlari", "MusteriId");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
        => migrationBuilder.DropTable("RentACarKaraListeKayitlari");
}
