using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MKFiloServis.Web.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260925010000_RentACarOdemeTakibi")]
public sealed class RentACarOdemeTakibi : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "RentACarOdemeHareketleri" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FirmaId" integer NOT NULL,
                    "MusteriKiralamaId" integer NOT NULL,
                    "IslemTarihi" timestamp with time zone NOT NULL,
                    "HareketTuru" integer NOT NULL,
                    "OdemeYontemi" integer NOT NULL,
                    "Tutar" numeric(18,2) NOT NULL,
                    "BelgeNo" character varying(100),
                    "Aciklama" character varying(500),
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                    "DeletedAt" timestamp with time zone,
                    "DeletedBy" integer,
                    CONSTRAINT "FK_RentACarOdemeHareketleri_Firmalar_FirmaId" FOREIGN KEY ("FirmaId") REFERENCES "Firmalar" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_RentACarOdemeHareketleri_MusteriKiralamalar_MusteriKiralamaId" FOREIGN KEY ("MusteriKiralamaId") REFERENCES "MusteriKiralamalar" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_RentACarOdemeHareketleri_FirmaId_MusteriKiralamaId_IslemTarihi"
                    ON "RentACarOdemeHareketleri" ("FirmaId", "MusteriKiralamaId", "IslemTarihi");
                CREATE INDEX IF NOT EXISTS "IX_RentACarOdemeHareketleri_MusteriKiralamaId"
                    ON "RentACarOdemeHareketleri" ("MusteriKiralamaId");
                """);
            return;
        }

        migrationBuilder.CreateTable(
            name: "RentACarOdemeHareketleri",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true),
                FirmaId = table.Column<int>(nullable: false),
                MusteriKiralamaId = table.Column<int>(nullable: false),
                IslemTarihi = table.Column<DateTime>(nullable: false),
                HareketTuru = table.Column<int>(nullable: false),
                OdemeYontemi = table.Column<int>(nullable: false),
                Tutar = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                BelgeNo = table.Column<string>(maxLength: 100, nullable: true),
                Aciklama = table.Column<string>(maxLength: 500, nullable: true),
                CreatedAt = table.Column<DateTime>(nullable: false),
                UpdatedAt = table.Column<DateTime>(nullable: true),
                IsDeleted = table.Column<bool>(nullable: false),
                DeletedAt = table.Column<DateTime>(nullable: true),
                DeletedBy = table.Column<int>(nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_RentACarOdemeHareketleri", x => x.Id);
                table.ForeignKey("FK_RentACarOdemeHareketleri_Firmalar_FirmaId", x => x.FirmaId, "Firmalar", "Id", onDelete: ReferentialAction.Restrict);
                table.ForeignKey("FK_RentACarOdemeHareketleri_MusteriKiralamalar_MusteriKiralamaId", x => x.MusteriKiralamaId, "MusteriKiralamalar", "Id", onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateIndex(
            name: "IX_RentACarOdemeHareketleri_FirmaId_MusteriKiralamaId_IslemTarihi",
            table: "RentACarOdemeHareketleri",
            columns: new[] { "FirmaId", "MusteriKiralamaId", "IslemTarihi" });
        migrationBuilder.CreateIndex(
            name: "IX_RentACarOdemeHareketleri_MusteriKiralamaId",
            table: "RentACarOdemeHareketleri",
            column: "MusteriKiralamaId");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
        => migrationBuilder.DropTable(name: "RentACarOdemeHareketleri");
}
