using System.Data;
using MKFiloServis.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace MKFiloServis.Web.Data.Migrations;

public static class BordroMigrationHelper
{
    public static async Task ApplyBordroTablolariAsync(ApplicationDbContext context)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                var sql = @"
                    CREATE TABLE IF NOT EXISTS ""BordroAyarlar"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""FirmaId"" integer NULL,
                        ""PersonelMaasHesapKodu"" text NOT NULL DEFAULT '335',
                        ""SgkPrimHesapKodu"" text NOT NULL DEFAULT '361',
                        ""GelirVergisiHesapKodu"" text NOT NULL DEFAULT '360',
                        ""KasaHesapKodu"" text NOT NULL DEFAULT '100',
                        ""BankaHesapKodu"" text NOT NULL DEFAULT '102',
                        ""PersonelAvansHesapKodu"" text NOT NULL DEFAULT '195',
                        ""SgkIsciPayiOrani"" numeric(18,2) NOT NULL DEFAULT 14,
                        ""IssizlikIsciPayiOrani"" numeric(18,2) NOT NULL DEFAULT 1,
                        ""DamgaVergisiOrani"" numeric(18,3) NOT NULL DEFAULT 0.759,
                        ""ArgeSgkIsverenDestekVarMi"" boolean NOT NULL DEFAULT TRUE,
                        ""ArgeSgkIsverenDestekOrani"" numeric(18,2) NOT NULL DEFAULT 100
                    );

                    CREATE TABLE IF NOT EXISTS ""Bordrolar"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""Yil"" integer NOT NULL,
                        ""Ay"" integer NOT NULL,
                        ""FirmaId"" integer NULL,
                        ""BordroTipi"" integer NOT NULL,
                        ""HesaplamaTarihi"" timestamp with time zone NULL,
                        ""OnayTarihi"" timestamp with time zone NULL,
                        ""Onaylandi"" boolean NOT NULL DEFAULT FALSE,
                        ""OnaylayanKullanici"" text NULL,
                        ""Aciklama"" text NULL,
                        ""ToplamPersonelSayisi"" integer NOT NULL DEFAULT 0,
                        ""ToplamBrutMaas"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""ToplamNetMaas"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""ToplamSgkMatrahi"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""ToplamEkOdeme"" numeric(18,2) NOT NULL DEFAULT 0
                    );

                    CREATE TABLE IF NOT EXISTS ""BordroDetaylar"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""BordroId"" integer NOT NULL,
                        ""PersonelId"" integer NOT NULL,
                        ""FirmaId"" integer NULL,
                        ""BrutMaas"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""NetMaas"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""TopluMaas"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""SgkMaasi"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""EkOdeme"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""SgkIssizlikKesinti"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""GelirVergisi"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""DamgaVergisi"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""YemekYardimi"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""YolYardimi"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""PrimTutar"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""DigerEkOdeme"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""BankaOdemesiYapildi"" boolean NOT NULL DEFAULT FALSE,
                        ""BankaOdemeTarihi"" timestamp with time zone NULL,
                        ""EkOdemeYapildi"" boolean NOT NULL DEFAULT FALSE,
                        ""EkOdemeTarihi"" timestamp with time zone NULL,
                        ""Notlar"" text NULL
                    );

                    CREATE TABLE IF NOT EXISTS ""BordroOdemeler"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""BordroDetayId"" integer NOT NULL,
                        ""OdemeTipi"" integer NOT NULL,
                        ""OdemeTarihi"" timestamp with time zone NOT NULL,
                        ""OdemeTutari"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""OdemeSekli"" integer NOT NULL,
                        ""BankaHesapId"" integer NULL,
                        ""EvrakNo"" text NULL,
                        ""Aciklama"" text NULL,
                        ""MuhasebeFisId"" integer NULL
                    );
                ";

                await context.Database.ExecuteSqlRawAsync(sql);
                return;
            }

            if (context.Database.IsSqlite())
            {
                await EnsureSqliteTableAsync(context, """
                    CREATE TABLE IF NOT EXISTS "BordroAyarlar" (
                        "Id" INTEGER NOT NULL CONSTRAINT "PK_BordroAyarlar" PRIMARY KEY AUTOINCREMENT,
                        "CreatedAt" TEXT NOT NULL,
                        "UpdatedAt" TEXT NULL,
                        "IsDeleted" INTEGER NOT NULL DEFAULT 0,
                        "FirmaId" INTEGER NULL,
                        "PersonelMaasHesapKodu" TEXT NOT NULL DEFAULT '335',
                        "SgkPrimHesapKodu" TEXT NOT NULL DEFAULT '361',
                        "GelirVergisiHesapKodu" TEXT NOT NULL DEFAULT '360',
                        "KasaHesapKodu" TEXT NOT NULL DEFAULT '100',
                        "BankaHesapKodu" TEXT NOT NULL DEFAULT '102',
                        "PersonelAvansHesapKodu" TEXT NOT NULL DEFAULT '195',
                        "SgkIsciPayiOrani" TEXT NOT NULL DEFAULT '14',
                        "IssizlikIsciPayiOrani" TEXT NOT NULL DEFAULT '1',
                        "DamgaVergisiOrani" TEXT NOT NULL DEFAULT '0.759',
                        "ArgeSgkIsverenDestekVarMi" INTEGER NOT NULL DEFAULT 1,
                        "ArgeSgkIsverenDestekOrani" TEXT NOT NULL DEFAULT '100'
                    )
                    """);

                await EnsureSqliteTableAsync(context, """
                    CREATE TABLE IF NOT EXISTS "Bordrolar" (
                        "Id" INTEGER NOT NULL CONSTRAINT "PK_Bordrolar" PRIMARY KEY AUTOINCREMENT,
                        "CreatedAt" TEXT NOT NULL,
                        "UpdatedAt" TEXT NULL,
                        "IsDeleted" INTEGER NOT NULL DEFAULT 0,
                        "Yil" INTEGER NOT NULL,
                        "Ay" INTEGER NOT NULL,
                        "FirmaId" INTEGER NULL,
                        "BordroTipi" INTEGER NOT NULL,
                        "HesaplamaTarihi" TEXT NULL,
                        "OnayTarihi" TEXT NULL,
                        "Onaylandi" INTEGER NOT NULL DEFAULT 0,
                        "OnaylayanKullanici" TEXT NULL,
                        "Aciklama" TEXT NULL,
                        "ToplamPersonelSayisi" INTEGER NOT NULL DEFAULT 0,
                        "ToplamBrutMaas" TEXT NOT NULL DEFAULT '0',
                        "ToplamNetMaas" TEXT NOT NULL DEFAULT '0',
                        "ToplamSgkMatrahi" TEXT NOT NULL DEFAULT '0',
                        "ToplamEkOdeme" TEXT NOT NULL DEFAULT '0'
                    )
                    """);

                await EnsureSqliteTableAsync(context, """
                    CREATE TABLE IF NOT EXISTS "BordroDetaylar" (
                        "Id" INTEGER NOT NULL CONSTRAINT "PK_BordroDetaylar" PRIMARY KEY AUTOINCREMENT,
                        "CreatedAt" TEXT NOT NULL,
                        "UpdatedAt" TEXT NULL,
                        "IsDeleted" INTEGER NOT NULL DEFAULT 0,
                        "BordroId" INTEGER NOT NULL,
                        "PersonelId" INTEGER NOT NULL,
                        "FirmaId" INTEGER NULL,
                        "BrutMaas" TEXT NOT NULL DEFAULT '0',
                        "NetMaas" TEXT NOT NULL DEFAULT '0',
                        "TopluMaas" TEXT NOT NULL DEFAULT '0',
                        "SgkMaasi" TEXT NOT NULL DEFAULT '0',
                        "EkOdeme" TEXT NOT NULL DEFAULT '0',
                        "SgkIssizlikKesinti" TEXT NOT NULL DEFAULT '0',
                        "GelirVergisi" TEXT NOT NULL DEFAULT '0',
                        "DamgaVergisi" TEXT NOT NULL DEFAULT '0',
                        "YemekYardimi" TEXT NOT NULL DEFAULT '0',
                        "YolYardimi" TEXT NOT NULL DEFAULT '0',
                        "PrimTutar" TEXT NOT NULL DEFAULT '0',
                        "DigerEkOdeme" TEXT NOT NULL DEFAULT '0',
                        "BankaOdemesiYapildi" INTEGER NOT NULL DEFAULT 0,
                        "BankaOdemeTarihi" TEXT NULL,
                        "EkOdemeYapildi" INTEGER NOT NULL DEFAULT 0,
                        "EkOdemeTarihi" TEXT NULL,
                        "Notlar" TEXT NULL
                    )
                    """);

                await EnsureSqliteTableAsync(context, """
                    CREATE TABLE IF NOT EXISTS "BordroOdemeler" (
                        "Id" INTEGER NOT NULL CONSTRAINT "PK_BordroOdemeler" PRIMARY KEY AUTOINCREMENT,
                        "CreatedAt" TEXT NOT NULL,
                        "UpdatedAt" TEXT NULL,
                        "IsDeleted" INTEGER NOT NULL DEFAULT 0,
                        "BordroDetayId" INTEGER NOT NULL,
                        "OdemeTipi" INTEGER NOT NULL,
                        "OdemeTarihi" TEXT NOT NULL,
                        "OdemeTutari" TEXT NOT NULL DEFAULT '0',
                        "OdemeSekli" INTEGER NOT NULL,
                        "BankaHesapId" INTEGER NULL,
                        "EvrakNo" TEXT NULL,
                        "Aciklama" TEXT NULL,
                        "MuhasebeFisId" INTEGER NULL
                    )
                    """);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Bordro tabloları migration hatası: {ex.Message}");
        }
    }

    private static async Task EnsureSqliteTableAsync(ApplicationDbContext context, string createTableSql)
    {
        var connection = context.Database.GetDbConnection();
        var shouldClose = connection.State != ConnectionState.Open;

        if (shouldClose)
        {
            await connection.OpenAsync();
        }

        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText = createTableSql;
            await command.ExecuteNonQueryAsync();
        }
        finally
        {
            if (shouldClose)
            {
                await connection.CloseAsync();
            }
        }
    }
}



