using System.Data;
using Microsoft.EntityFrameworkCore;
using MKFiloServis.Web.Data;

namespace MKFiloServis.Web.Data.Migrations;

/// <summary>
/// BudgetHedefler tablosunu güvenli şekilde oluşturur.
/// </summary>
public static class BudgetHedefMigrationHelper
{
    public static async Task EnsureBudgetHedefTableAsync(ApplicationDbContext context)
    {
        if (context.Database.IsNpgsql())
        {
            var sql = @"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'BudgetHedefler') THEN
        CREATE TABLE ""BudgetHedefler"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""Yil"" integer NOT NULL,
            ""Ay"" integer NOT NULL,
            ""MasrafKalemi"" text NOT NULL,
            ""HedefTutar"" numeric NOT NULL,
            ""Aciklama"" text NULL,
            ""FirmaId"" integer NULL,
            ""CreatedAt"" timestamp without time zone NOT NULL,
            ""UpdatedAt"" timestamp without time zone NULL,
            ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
            CONSTRAINT ""FK_BudgetHedefler_Firmalar_FirmaId"" FOREIGN KEY (""FirmaId"") REFERENCES ""Firmalar"" (""Id"")
        );

        CREATE INDEX ""IX_BudgetHedefler_FirmaId"" ON ""BudgetHedefler"" (""FirmaId"");
        CREATE INDEX ""IX_BudgetHedefler_Yil_Ay"" ON ""BudgetHedefler"" (""Yil"", ""Ay"");
        CREATE INDEX ""IX_BudgetHedefler_MasrafKalemi"" ON ""BudgetHedefler"" (""MasrafKalemi"");
    END IF;
END $$;";

            await context.Database.ExecuteSqlRawAsync(sql);
            return;
        }

        if (context.Database.IsSqlite())
        {
            await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""BudgetHedefler"" (
    ""Id"" INTEGER PRIMARY KEY AUTOINCREMENT,
    ""Yil"" INTEGER NOT NULL,
    ""Ay"" INTEGER NOT NULL,
    ""MasrafKalemi"" TEXT NOT NULL,
    ""HedefTutar"" REAL NOT NULL,
    ""Aciklama"" TEXT NULL,
    ""FirmaId"" INTEGER NULL,
    ""CreatedAt"" TEXT NOT NULL,
    ""UpdatedAt"" TEXT NULL,
    ""IsDeleted"" INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (""FirmaId"") REFERENCES ""Firmalar"" (""Id"")
);");

            await context.Database.ExecuteSqlRawAsync(@"CREATE INDEX IF NOT EXISTS ""IX_BudgetHedefler_FirmaId"" ON ""BudgetHedefler"" (""FirmaId"");");
            await context.Database.ExecuteSqlRawAsync(@"CREATE INDEX IF NOT EXISTS ""IX_BudgetHedefler_Yil_Ay"" ON ""BudgetHedefler"" (""Yil"", ""Ay"");");
            await context.Database.ExecuteSqlRawAsync(@"CREATE INDEX IF NOT EXISTS ""IX_BudgetHedefler_MasrafKalemi"" ON ""BudgetHedefler"" (""MasrafKalemi"");");
        }
    }
}



