using System.Data;
using MKFiloServis.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace MKFiloServis.Web.Data.Migrations;

public static class PersonelFinansMigrationHelper
{
    public static async Task ApplyPersonelFinansTablolariAsync(ApplicationDbContext context)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                // Önce tabloları foreign key olmadan oluştur
                var createTablesSql = @"
                    -- Personel Avanslar Tablosu
                    CREATE TABLE IF NOT EXISTS ""PersonelAvanslar"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""PersonelId"" integer NOT NULL,
                        ""FirmaId"" integer NULL,
                        ""AvansTarihi"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""Tutar"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""Aciklama"" text NULL,
                        ""OdemeSekli"" integer NOT NULL DEFAULT 1,
                        ""BankaHesapId"" integer NULL,
                        ""MuhasebeFisId"" integer NULL,
                        ""Durum"" integer NOT NULL DEFAULT 1,
                        ""MahsupEdilen"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""MahsupTarihi"" timestamp with time zone NULL,
                        ""MahsupAciklamasi"" text NULL
                    );

                    CREATE INDEX IF NOT EXISTS ""IX_PersonelAvanslar_PersonelId"" ON ""PersonelAvanslar"" (""PersonelId"");
                    CREATE INDEX IF NOT EXISTS ""IX_PersonelAvanslar_FirmaId"" ON ""PersonelAvanslar"" (""FirmaId"");
                    CREATE INDEX IF NOT EXISTS ""IX_PersonelAvanslar_AvansTarihi"" ON ""PersonelAvanslar"" (""AvansTarihi"");
                    CREATE INDEX IF NOT EXISTS ""IX_PersonelAvanslar_Durum"" ON ""PersonelAvanslar"" (""Durum"");

                    -- Personel Borclar Tablosu
                    CREATE TABLE IF NOT EXISTS ""PersonelBorclar"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""PersonelId"" integer NOT NULL,
                        ""FirmaId"" integer NULL,
                        ""BorcTarihi"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""Tutar"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""BorcNedeni"" text NOT NULL DEFAULT '',
                        ""Aciklama"" text NULL,
                        ""BorcTipi"" integer NOT NULL DEFAULT 1,
                        ""OdemeDurum"" integer NOT NULL DEFAULT 1,
                        ""PlanlananOdemeTarihi"" timestamp with time zone NULL,
                        ""GerceklesenOdemeTarihi"" timestamp with time zone NULL,
                        ""OdenenTutar"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""OdemeSekli"" integer NULL,
                        ""BankaHesapId"" integer NULL,
                        ""MuhasebeFisId"" integer NULL
                    );

                    CREATE INDEX IF NOT EXISTS ""IX_PersonelBorclar_PersonelId"" ON ""PersonelBorclar"" (""PersonelId"");
                    CREATE INDEX IF NOT EXISTS ""IX_PersonelBorclar_FirmaId"" ON ""PersonelBorclar"" (""FirmaId"");
                    CREATE INDEX IF NOT EXISTS ""IX_PersonelBorclar_BorcTarihi"" ON ""PersonelBorclar"" (""BorcTarihi"");
                    CREATE INDEX IF NOT EXISTS ""IX_PersonelBorclar_OdemeDurum"" ON ""PersonelBorclar"" (""OdemeDurum"");

                    -- Personel Avans Mahsup Tablosu
                    CREATE TABLE IF NOT EXISTS ""PersonelAvansMahsuplar"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""AvansId"" integer NOT NULL,
                        ""MahsupTarihi"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""MahsupTutari"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""Aciklama"" text NULL,
                        ""MahsupSekli"" integer NOT NULL DEFAULT 1,
                        ""MaasId"" integer NULL,
                        ""BankaHesapId"" integer NULL
                    );

                    CREATE INDEX IF NOT EXISTS ""IX_PersonelAvansMahsuplar_AvansId"" ON ""PersonelAvansMahsuplar"" (""AvansId"");

                    -- Personel Borc Odeme Tablosu
                    CREATE TABLE IF NOT EXISTS ""PersonelBorcOdemeler"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""BorcId"" integer NOT NULL,
                        ""OdemeTarihi"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""OdemeTutari"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""Aciklama"" text NULL,
                        ""OdemeSekli"" integer NOT NULL DEFAULT 1,
                        ""BankaHesapId"" integer NULL,
                        ""MuhasebeFisId"" integer NULL
                    );

                    CREATE INDEX IF NOT EXISTS ""IX_PersonelBorcOdemeler_BorcId"" ON ""PersonelBorcOdemeler"" (""BorcId"");

                    -- Personel Finans Ayarlar Tablosu
                    CREATE TABLE IF NOT EXISTS ""PersonelFinansAyarlar"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL,
                        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                        ""FirmaId"" integer NULL,
                        ""PersonelAvanslariHesapId"" integer NULL,
                        ""PersoneleBorclarHesapId"" integer NULL,
                        ""KasaHesapId"" integer NULL,
                        ""BankaHesapId"" integer NULL,
                        ""OtomatikFisOlustur"" boolean NOT NULL DEFAULT TRUE,
                        ""AvansVerildigindeFisOlustur"" boolean NOT NULL DEFAULT TRUE,
                        ""AvansMahsupFisOlustur"" boolean NOT NULL DEFAULT TRUE,
                        ""BorcOdendigindeFisOlustur"" boolean NOT NULL DEFAULT TRUE
                    );

                    CREATE INDEX IF NOT EXISTS ""IX_PersonelFinansAyarlar_FirmaId"" ON ""PersonelFinansAyarlar"" (""FirmaId"");
                ";

                await context.Database.ExecuteSqlRawAsync(createTablesSql);

                // Foreign key'leri ayrı olarak ekle (referans edilen tablolar varsa)
                var addForeignKeysSql = @"
                    -- PersonelAvanslar foreign key'leri
                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Soforler') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelAvanslar_Soforler') THEN
                            ALTER TABLE ""PersonelAvanslar"" ADD CONSTRAINT ""FK_PersonelAvanslar_Soforler"" 
                                FOREIGN KEY (""PersonelId"") REFERENCES ""Soforler"" (""Id"") ON DELETE CASCADE;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Firmalar') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelAvanslar_Firmalar') THEN
                            ALTER TABLE ""PersonelAvanslar"" ADD CONSTRAINT ""FK_PersonelAvanslar_Firmalar"" 
                                FOREIGN KEY (""FirmaId"") REFERENCES ""Firmalar"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'BankaHesaplari') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelAvanslar_BankaHesaplari') THEN
                            ALTER TABLE ""PersonelAvanslar"" ADD CONSTRAINT ""FK_PersonelAvanslar_BankaHesaplari"" 
                                FOREIGN KEY (""BankaHesapId"") REFERENCES ""BankaHesaplari"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'MuhasebeFisler') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelAvanslar_MuhasebeFisler') THEN
                            ALTER TABLE ""PersonelAvanslar"" ADD CONSTRAINT ""FK_PersonelAvanslar_MuhasebeFisler"" 
                                FOREIGN KEY (""MuhasebeFisId"") REFERENCES ""MuhasebeFisler"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    -- PersonelBorclar foreign key'leri
                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Soforler') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelBorclar_Soforler') THEN
                            ALTER TABLE ""PersonelBorclar"" ADD CONSTRAINT ""FK_PersonelBorclar_Soforler"" 
                                FOREIGN KEY (""PersonelId"") REFERENCES ""Soforler"" (""Id"") ON DELETE CASCADE;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Firmalar') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelBorclar_Firmalar') THEN
                            ALTER TABLE ""PersonelBorclar"" ADD CONSTRAINT ""FK_PersonelBorclar_Firmalar"" 
                                FOREIGN KEY (""FirmaId"") REFERENCES ""Firmalar"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'BankaHesaplari') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelBorclar_BankaHesaplari') THEN
                            ALTER TABLE ""PersonelBorclar"" ADD CONSTRAINT ""FK_PersonelBorclar_BankaHesaplari"" 
                                FOREIGN KEY (""BankaHesapId"") REFERENCES ""BankaHesaplari"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'MuhasebeFisler') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelBorclar_MuhasebeFisler') THEN
                            ALTER TABLE ""PersonelBorclar"" ADD CONSTRAINT ""FK_PersonelBorclar_MuhasebeFisler"" 
                                FOREIGN KEY (""MuhasebeFisId"") REFERENCES ""MuhasebeFisler"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    -- PersonelAvansMahsuplar foreign key'leri
                    DO $$ BEGIN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelAvansMahsuplar_Avanslar') THEN
                            ALTER TABLE ""PersonelAvansMahsuplar"" ADD CONSTRAINT ""FK_PersonelAvansMahsuplar_Avanslar"" 
                                FOREIGN KEY (""AvansId"") REFERENCES ""PersonelAvanslar"" (""Id"") ON DELETE CASCADE;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'BankaHesaplari') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelAvansMahsuplar_BankaHesaplari') THEN
                            ALTER TABLE ""PersonelAvansMahsuplar"" ADD CONSTRAINT ""FK_PersonelAvansMahsuplar_BankaHesaplari"" 
                                FOREIGN KEY (""BankaHesapId"") REFERENCES ""BankaHesaplari"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    -- PersonelBorcOdemeler foreign key'leri
                    DO $$ BEGIN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelBorcOdemeler_Borclar') THEN
                            ALTER TABLE ""PersonelBorcOdemeler"" ADD CONSTRAINT ""FK_PersonelBorcOdemeler_Borclar"" 
                                FOREIGN KEY (""BorcId"") REFERENCES ""PersonelBorclar"" (""Id"") ON DELETE CASCADE;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'BankaHesaplari') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelBorcOdemeler_BankaHesaplari') THEN
                            ALTER TABLE ""PersonelBorcOdemeler"" ADD CONSTRAINT ""FK_PersonelBorcOdemeler_BankaHesaplari"" 
                                FOREIGN KEY (""BankaHesapId"") REFERENCES ""BankaHesaplari"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'MuhasebeFisler') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelBorcOdemeler_MuhasebeFisler') THEN
                            ALTER TABLE ""PersonelBorcOdemeler"" ADD CONSTRAINT ""FK_PersonelBorcOdemeler_MuhasebeFisler"" 
                                FOREIGN KEY (""MuhasebeFisId"") REFERENCES ""MuhasebeFisler"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    -- PersonelFinansAyarlar foreign key'leri
                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Firmalar') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelFinansAyarlar_Firmalar') THEN
                            ALTER TABLE ""PersonelFinansAyarlar"" ADD CONSTRAINT ""FK_PersonelFinansAyarlar_Firmalar"" 
                                FOREIGN KEY (""FirmaId"") REFERENCES ""Firmalar"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'MuhasebeHesaplar') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelFinansAyarlar_PersonelAvanslariHesap') THEN
                            ALTER TABLE ""PersonelFinansAyarlar"" ADD CONSTRAINT ""FK_PersonelFinansAyarlar_PersonelAvanslariHesap"" 
                                FOREIGN KEY (""PersonelAvanslariHesapId"") REFERENCES ""MuhasebeHesaplar"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'MuhasebeHesaplar') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelFinansAyarlar_PersoneleBorclarHesap') THEN
                            ALTER TABLE ""PersonelFinansAyarlar"" ADD CONSTRAINT ""FK_PersonelFinansAyarlar_PersoneleBorclarHesap"" 
                                FOREIGN KEY (""PersoneleBorclarHesapId"") REFERENCES ""MuhasebeHesaplar"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'MuhasebeHesaplar') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelFinansAyarlar_KasaHesap') THEN
                            ALTER TABLE ""PersonelFinansAyarlar"" ADD CONSTRAINT ""FK_PersonelFinansAyarlar_KasaHesap"" 
                                FOREIGN KEY (""KasaHesapId"") REFERENCES ""MuhasebeHesaplar"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;

                    DO $$ BEGIN
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'MuhasebeHesaplar') 
                           AND NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_PersonelFinansAyarlar_BankaHesap') THEN
                            ALTER TABLE ""PersonelFinansAyarlar"" ADD CONSTRAINT ""FK_PersonelFinansAyarlar_BankaHesap"" 
                                FOREIGN KEY (""BankaHesapId"") REFERENCES ""MuhasebeHesaplar"" (""Id"") ON DELETE SET NULL;
                        END IF;
                    END $$;
                ";

                await context.Database.ExecuteSqlRawAsync(addForeignKeysSql);
                Console.WriteLine("PersonelFinans tabloları başarıyla oluşturuldu.");
                return;
            }

            if (context.Database.IsSqlite())
            {
                // SQLite için tablolar
                await EnsureSqliteTableAsync(context, @"
                    CREATE TABLE IF NOT EXISTS ""PersonelAvanslar"" (
                        ""Id"" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        ""CreatedAt"" TEXT NOT NULL,
                        ""UpdatedAt"" TEXT NULL,
                        ""IsDeleted"" INTEGER NOT NULL DEFAULT 0,
                        ""PersonelId"" INTEGER NOT NULL,
                        ""FirmaId"" INTEGER NULL,
                        ""AvansTarihi"" TEXT NOT NULL,
                        ""Tutar"" TEXT NOT NULL DEFAULT '0',
                        ""Aciklama"" TEXT NULL,
                        ""OdemeSekli"" INTEGER NOT NULL DEFAULT 1,
                        ""BankaHesapId"" INTEGER NULL,
                        ""MuhasebeFisId"" INTEGER NULL,
                        ""Durum"" INTEGER NOT NULL DEFAULT 1,
                        ""MahsupEdilen"" TEXT NOT NULL DEFAULT '0',
                        ""MahsupTarihi"" TEXT NULL,
                        ""MahsupAciklamasi"" TEXT NULL
                    )
                ");

                await EnsureSqliteTableAsync(context, @"
                    CREATE TABLE IF NOT EXISTS ""PersonelBorclar"" (
                        ""Id"" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        ""CreatedAt"" TEXT NOT NULL,
                        ""UpdatedAt"" TEXT NULL,
                        ""IsDeleted"" INTEGER NOT NULL DEFAULT 0,
                        ""PersonelId"" INTEGER NOT NULL,
                        ""FirmaId"" INTEGER NULL,
                        ""BorcTarihi"" TEXT NOT NULL,
                        ""Tutar"" TEXT NOT NULL DEFAULT '0',
                        ""BorcNedeni"" TEXT NOT NULL DEFAULT '',
                        ""Aciklama"" TEXT NULL,
                        ""BorcTipi"" INTEGER NOT NULL DEFAULT 1,
                        ""OdemeDurum"" INTEGER NOT NULL DEFAULT 1,
                        ""PlanlananOdemeTarihi"" TEXT NULL,
                        ""GerceklesenOdemeTarihi"" TEXT NULL,
                        ""OdenenTutar"" TEXT NOT NULL DEFAULT '0',
                        ""OdemeSekli"" INTEGER NULL,
                        ""BankaHesapId"" INTEGER NULL,
                        ""MuhasebeFisId"" INTEGER NULL
                    )
                ");

                await EnsureSqliteTableAsync(context, @"
                    CREATE TABLE IF NOT EXISTS ""PersonelAvansMahsuplar"" (
                        ""Id"" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        ""CreatedAt"" TEXT NOT NULL,
                        ""UpdatedAt"" TEXT NULL,
                        ""IsDeleted"" INTEGER NOT NULL DEFAULT 0,
                        ""AvansId"" INTEGER NOT NULL,
                        ""MahsupTarihi"" TEXT NOT NULL,
                        ""MahsupTutari"" TEXT NOT NULL DEFAULT '0',
                        ""Aciklama"" TEXT NULL,
                        ""MahsupSekli"" INTEGER NOT NULL DEFAULT 1,
                        ""MaasId"" INTEGER NULL,
                        ""BankaHesapId"" INTEGER NULL
                    )
                ");

                await EnsureSqliteTableAsync(context, @"
                    CREATE TABLE IF NOT EXISTS ""PersonelBorcOdemeler"" (
                        ""Id"" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        ""CreatedAt"" TEXT NOT NULL,
                        ""UpdatedAt"" TEXT NULL,
                        ""IsDeleted"" INTEGER NOT NULL DEFAULT 0,
                        ""BorcId"" INTEGER NOT NULL,
                        ""OdemeTarihi"" TEXT NOT NULL,
                        ""OdemeTutari"" TEXT NOT NULL DEFAULT '0',
                        ""Aciklama"" TEXT NULL,
                        ""OdemeSekli"" INTEGER NOT NULL DEFAULT 1,
                        ""BankaHesapId"" INTEGER NULL,
                        ""MuhasebeFisId"" INTEGER NULL
                    )
                ");

                await EnsureSqliteTableAsync(context, @"
                    CREATE TABLE IF NOT EXISTS ""PersonelFinansAyarlar"" (
                        ""Id"" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        ""CreatedAt"" TEXT NOT NULL,
                        ""UpdatedAt"" TEXT NULL,
                        ""IsDeleted"" INTEGER NOT NULL DEFAULT 0,
                        ""FirmaId"" INTEGER NULL,
                        ""PersonelAvanslariHesapId"" INTEGER NULL,
                        ""PersoneleBorclarHesapId"" INTEGER NULL,
                        ""KasaHesapId"" INTEGER NULL,
                        ""BankaHesapId"" INTEGER NULL,
                        ""OtomatikFisOlustur"" INTEGER NOT NULL DEFAULT 1,
                        ""AvansVerildigindeFisOlustur"" INTEGER NOT NULL DEFAULT 1,
                        ""AvansMahsupFisOlustur"" INTEGER NOT NULL DEFAULT 1,
                        ""BorcOdendigindeFisOlustur"" INTEGER NOT NULL DEFAULT 1
                    )
                ");

                Console.WriteLine("PersonelFinans tabloları (SQLite) başarıyla oluşturuldu.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"PersonelFinans tabloları oluşturma hatası: {ex.Message}");
            throw;
        }
    }

    private static async Task EnsureSqliteTableAsync(ApplicationDbContext context, string createTableSql)
    {
        var connection = context.Database.GetDbConnection();
        var shouldClose = connection.State != ConnectionState.Open;

        if (shouldClose)
        {
            await connection.OpenAsync();
        }

        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText = createTableSql;
            await command.ExecuteNonQueryAsync();
        }
        finally
        {
            if (shouldClose)
            {
                await connection.CloseAsync();
            }
        }
    }
}



